{
 "title": "My Nest.js Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(workerId) (rate(sso_process_cpu_utilization{process_cpu_state=\"user\"}[1m]))*10000",
     "legendFormat": "Worker {{workerId}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (workerId) (sso_process_memory_usage / 1048576)",
     "legendFormat": "Worker {{workerId}}"
    }
   ]
  },
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "P99 response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, workerId, method, path) (rate(sso_api_http_server_duration_bucket[1m])))",
     "legendFormat": "{{workerId}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "P90 response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, workerId, method, path) (rate(sso_api_http_server_duration_bucket[1m])))",
     "legendFormat": "{{workerId}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "P50 response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, workerId, method, path) (rate(sso_api_http_server_duration_bucket[1m])))",
     "legendFormat": "{{workerId}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Responses by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status, method) (increase(sso_api_http_server_duration_count[1m]))",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Throughput by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(sso_api_http_server_duration_count[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top HTTP paths used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(workerId, path) (increase(sso_api_http_server_duration_count[1m]))",
     "legendFormat": "{{workerId}} {{path}}"
    }
   ]
  },
  {
   "title": "Probe Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (workerId) (rate(sso_api_http_server_duration_count{status=~\"[45]..\"}[1m])) / sum by (workerId) (rate(sso_api_http_server_duration_count[1m]))",
     "legendFormat": "Worker {{workerId}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(workerId, path) (rate(sso_api_http_server_duration_sum[1m])) / sum by(workerId, path) (rate(sso_api_http_server_duration_count[1m]))",
     "legendFormat": "{{workerId}} {{path}}"
    }
   ]
  },
  {
   "title": "Top HTTP paths used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(workerId) (increase(sso_api_http_server_duration_count[1m]))",
     "legendFormat": "{{workerId}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(workerId) (rate(sso_api_http_server_duration_count[1m]))",
     "legendFormat": "Worker {{workerId}}"
    }
   ]
  }
 ]
}